corner-radius = 12;
rounded-corners-exclude = [
  "window_type = 'dock'",
  "window_type = 'desktop'"
];

shadow = true;
shadow-radius = 12;
shadow-opacity = 0.4;
shadow-offset-x = -6;
shadow-offset-y = 6;

fading = true;
fade-in-step = 0.05;
fade-out-step = 0.05;

backend = "glx";
vsync = true;
