set -g default-terminal "tmux-256color"
set -as terminal-features ",alacritty:RGB"
set -ga terminal-overrides ",alacritty:Tc"

set -g mouse on
set -g set-clipboard on
setw -g mode-keys vi

set -g status-style "fg=default,bg=default"
set -g window-status-style "fg=default,bg=default"
set -g window-status-current-style "fg=default,bg=default,bold"
set -g pane-border-style "fg=default"
set -g pane-active-border-style "fg=default"
set -g message-style "fg=default,bg=default"
set -g mode-style "fg=default,bg=default,reverse"

bind-key -T copy-mode-vi y send-keys -X copy-pipe-and-cancel 'wl-copy'
bind-key -T copy-mode-vi Enter send-keys -X copy-pipe-and-cancel 'wl-copy'
bind-key -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-pipe-and-cancel 'wl-copy'

bind-key -T copy-mode Enter send-keys -X copy-pipe-and-cancel 'wl-copy'
bind-key -T copy-mode MouseDragEnd1Pane send-keys -X copy-pipe-and-cancel 'wl-copy'

bind-key P run-shell 'wl-paste --no-newline | tmux load-buffer - && tmux paste-buffer'
